version: '3.8'
services:
  playgroupdb:
    image: mysql:8.3
    command: --default-authentication-plugin=caching_sha2_password
    env_file:
      - .env
    environment:
      - "MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD"
      - "MYSQL_DATABASE=$MYSQLDB_DATABASE"
      - "MYSQL_USER=$MYSQLDB_USER"
      - "MYSQL_PASSWORD=$MYSQLDB_PASSWORD"
      - "MYSQL_CHARSET=utf8mb4"
      - "MYSQL_COLLATION=utf8mb4_unicode_ci"
    ports:
      - "$MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - playgroupdatabase:/var/lib/mysql
volumes:
  playgroupdatabase:

  playgroup:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    depends_on:
      - playgroupdb
    links:
      - playgroupdb
    ports:
      - "$NODE_LOCAL_PORT:$NODE_DOCKER_PORT"
